sudo: required
language: c

services:
  - docker

addons:
  apt:
    sources:
    - george-edison55-precise-backports # CMake 3.x
    packages:
    - check
    - cmake # Travis CI comes with CMake 2.8.7, we need CMake 2.8.11
    - cmake-data
    - libssl-dev
    - python-pip
    - nodejs

install:
  - pip install --user pytest ecdsa curve25519-donna

script:
  - make
  - ./tests
  - ./test-openssl 1000
  - ITERS=10 py.test
  - mkdir _build && cd _build
  - cmake ..
  - make
  - cd .. && cd emscripten && rm trezor-crypto.js && make docker-build && make test-correctness
