/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hyconTx.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hyconTx.pb-c.h"
void   hycon_txs__init
                     (HyconTxs         *message)
{
  static const HyconTxs init_value = HYCON_TXS__INIT;
  *message = init_value;
}
size_t hycon_txs__get_packed_size
                     (const HyconTxs *message)
{
  assert(message->base.descriptor == &hycon_txs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hycon_txs__pack
                     (const HyconTxs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hycon_txs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hycon_txs__pack_to_buffer
                     (const HyconTxs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hycon_txs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HyconTxs *
       hycon_txs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HyconTxs *)
     protobuf_c_message_unpack (&hycon_txs__descriptor,
                                allocator, len, data);
}
void   hycon_txs__free_unpacked
                     (HyconTxs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hycon_txs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hycon_tx__init
                     (HyconTx         *message)
{
  static const HyconTx init_value = HYCON_TX__INIT;
  *message = init_value;
}
size_t hycon_tx__get_packed_size
                     (const HyconTx *message)
{
  assert(message->base.descriptor == &hycon_tx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hycon_tx__pack
                     (const HyconTx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hycon_tx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hycon_tx__pack_to_buffer
                     (const HyconTx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hycon_tx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HyconTx *
       hycon_tx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HyconTx *)
     protobuf_c_message_unpack (&hycon_tx__descriptor,
                                allocator, len, data);
}
void   hycon_tx__free_unpacked
                     (HyconTx *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hycon_tx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hycon_txs__field_descriptors[1] =
{
  {
    "txs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HyconTxs, n_txs),
    offsetof(HyconTxs, txs),
    &hycon_tx__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hycon_txs__field_indices_by_name[] = {
  0,   /* field[0] = txs */
};
static const ProtobufCIntRange hycon_txs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hycon_txs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HyconTxs",
  "HyconTxs",
  "HyconTxs",
  "",
  sizeof(HyconTxs),
  1,
  hycon_txs__field_descriptors,
  hycon_txs__field_indices_by_name,
  1,  hycon_txs__number_ranges,
  (ProtobufCMessageInit) hycon_txs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hycon_tx__field_descriptors[7] =
{
  {
    "from",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HyconTx, from),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HyconTx, to),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(HyconTx, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(HyconTx, fee),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HyconTx, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HyconTx, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recovery",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HyconTx, recovery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hycon_tx__field_indices_by_name[] = {
  2,   /* field[2] = amount */
  3,   /* field[3] = fee */
  0,   /* field[0] = from */
  4,   /* field[4] = nonce */
  6,   /* field[6] = recovery */
  5,   /* field[5] = signature */
  1,   /* field[1] = to */
};
static const ProtobufCIntRange hycon_tx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor hycon_tx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HyconTx",
  "HyconTx",
  "HyconTx",
  "",
  sizeof(HyconTx),
  7,
  hycon_tx__field_descriptors,
  hycon_tx__field_indices_by_name,
  1,  hycon_tx__number_ranges,
  (ProtobufCMessageInit) hycon_tx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
