"undefined"===typeof importScripts&&"undefined"!==typeof WorkerGlobalScope&&this instanceof WorkerGlobalScope&&(this.importScripts=function(){throw Error("importScripts is a stub");});var e;e||(e=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);var ba=!1,l=!1,n=!1,ca=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)ba=!0;else if("WORKER"===e.ENVIRONMENT)l=!0;else if("NODE"===e.ENVIRONMENT)n=!0;else if("SHELL"===e.ENVIRONMENT)ca=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else ba="object"===typeof window,l="function"===typeof importScripts,n="object"===typeof process&&"function"===typeof require&&!ba&&!l,ca=!ba&&!n&&!l;
if(n){e.print||(e.print=console.log);e.printErr||(e.printErr=console.warn);var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);var c=da.readFileSync(a);return b?c:c.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};e.load=function(a){fa(read(a))};e.thisProgram||(e.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");e.arguments=process.argv.slice(2);"undefined"!==
typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof ga))throw a;});e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)e.print||(e.print=print),"undefined"!=typeof printErr&&(e.printErr=printErr),e.read="undefined"!=typeof read?read:function(){throw"no read() available";},e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?
e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)}),eval("if (typeof gc === 'function' && gc.toString().indexOf('[native code]') > 0) var gc = undefined");else if(ba||l)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),"undefined"!==typeof console?(e.print||(e.print=function(a){console.log(a)}),e.printErr||(e.printErr=function(a){console.warn(a)})):e.print||(e.print=function(){}),l&&(e.load=importScripts),"undefined"===typeof e.setWindowTitle&&(e.setWindowTitle=
function(a){document.title=a});else throw"Unknown runtime environment. Where are we?";function fa(a){eval.call(null,a)}!e.load&&e.read&&(e.load=function(a){fa(e.read(a))});e.print||(e.print=function(){});e.printErr||(e.printErr=e.print);e.arguments||(e.arguments=[]);e.thisProgram||(e.thisProgram="./this.program");e.quit||(e.quit=function(a,b){throw b;});e.print=e.print;e.N=e.printErr;e.preRun=[];e.postRun=[];for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);
var aa=void 0,u={Da:function(a){return tempRet0=a},Oa:function(){return tempRet0},P:function(){return q},H:function(a){q=a},va:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?u.V:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},Na:function(a){return Math.max(u.va(a),u.V)},Wc:16,td:function(a,b){"double"===b||"i64"===b?a&7&&(assert(4===(a&7)),a+=
4):assert(0===(a&3));return a},hd:function(a,b,c){return c||"i64"!=a&&"double"!=a?a?Math.min(b||(a?u.Na(a):0),u.V):Math.min(b,8):8},X:function(a,b,c){return c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b)},L:[],Ia:function(a){for(var b=0;b<u.L.length;b++)if(!u.L[b])return u.L[b]=a,2*(1+b);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},Ta:function(a){u.L[(a-2)/2]=null},A:function(a){u.A.fa||(u.A.fa={});u.A.fa[a]||
(u.A.fa[a]=1,e.N(a))},Z:{},ld:function(a,b){assert(b);u.Z[b]||(u.Z[b]={});var c=u.Z[b];c[a]||(c[a]=1===b.length?function(){return u.X(b,a)}:2===b.length?function(c){return u.X(b,a,[c])}:function(){return u.X(b,a,Array.prototype.slice.call(arguments))});return c[a]},jd:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},O:function(a){var b=q;q=q+a|0;q=q+15&-16;return b},ga:function(a){var b=y;y=y+a|0;y=y+15&
-16;return b},qa:function(a){var b=B[ha>>2];a=(b+a+15|0)&-16;B[ha>>2]=a;if(a=a>=C)ia(),a=!0;return a?(B[ha>>2]=b,0):b},ma:function(a,b){return Math.ceil(a/(b?b:16))*(b?b:16)},sd:function(a,b,c){return c?+(a>>>0)+4294967296*+(b>>>0):+(a>>>0)+4294967296*+(b|0)},U:1024,V:4,Xc:0};e.Runtime=u;u.addFunction=u.Ia;u.removeFunction=u.Ta;var ja=0;function assert(a,b){a||E("Assertion failed: "+b)}
function ka(a){var b=e["_"+a];if(!b)try{b=eval("_"+a)}catch(c){}assert(b,"Cannot call unknown function "+a+" (perhaps LLVM optimizations or closure removed it?)");return b}var la,ma;
(function(){function a(a){a=a.toString().match(f).slice(1);return{arguments:a[0],body:a[1],returnValue:a[2]}}function b(){if(!g){g={};for(var b in c)c.hasOwnProperty(b)&&(g[b]=a(c[b]))}}var c={stackSave:function(){u.P()},stackRestore:function(){u.H()},arrayToC:function(a){var b=u.O(a.length);na(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1,b=u.O(c);oa(a,b,c)}return b}},d={string:c.stringToC,array:c.arrayToC};ma=function(a,b,c,f,g){a=ka(a);var v=
[],z=0;if(f)for(var w=0;w<f.length;w++){var x=d[c[w]];x?(0===z&&(z=u.P()),v[w]=x(f[w])):v[w]=f[w]}c=a.apply(null,v);"string"===b&&(c=F(c));if(0!==z){if(g&&g.async){EmterpreterAsync.Zc.push(function(){u.H(z)});return}u.H(z)}return c};var f=/^function\s*[a-zA-Z$_0-9]*\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/,g=null;la=function(c,d,f){f=f||[];var t=ka(c);c=f.every(function(a){return"number"===a});var p="string"!==d;if(p&&c)return t;var v=f.map(function(a,b){return"$"+b});d="(function("+
v.join(",")+") {";var z=f.length;if(!c){b();d+="var stack = "+g.stackSave.body+";";for(var w=0;w<z;w++){var x=v[w],K=f[w];"number"!==K&&(K=g[K+"ToC"],d+="var "+K.arguments+" = "+x+";",d+=K.body+";",d+=x+"=("+K.returnValue+");")}}f=a(function(){return t}).returnValue;d+="var ret = "+f+"("+v.join(",")+");";p||(f=a(function(){return F}).returnValue,d+="ret = "+f+"(ret);");c||(b(),d+=g.stackRestore.body.replace("()","(stack)")+";");return eval(d+"return ret})")}})();e.ccall=ma;e.cwrap=la;
function pa(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":H[a>>0]=b;break;case "i8":H[a>>0]=b;break;case "i16":qa[a>>1]=b;break;case "i32":B[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+ra(tempDouble)?0<tempDouble?(sa(+ta(tempDouble/4294967296),4294967295)|0)>>>0:~~+ua((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];B[a>>2]=tempI64[0];B[a+4>>2]=tempI64[1];break;case "float":va[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:E("invalid type for setValue: "+
c)}}e.setValue=pa;function xa(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return H[a>>0];case "i8":return H[a>>0];case "i16":return qa[a>>1];case "i32":return B[a>>2];case "i64":return B[a>>2];case "float":return va[a>>2];case "double":return wa[a>>3];default:E("invalid type for setValue: "+b)}return null}e.getValue=xa;e.ALLOC_NORMAL=0;e.ALLOC_STACK=1;e.ALLOC_STATIC=2;e.ALLOC_DYNAMIC=3;e.ALLOC_NONE=4;
function ya(a,b,c,d){var f,g;"number"===typeof a?(f=!0,g=a):(f=!1,g=a.length);var h="string"===typeof b?b:null,m;4==c?m=d:m=["function"===typeof za?za:u.ga,u.O,u.ga,u.qa][void 0===c?2:c](Math.max(g,h?1:b.length));if(f){d=m;assert(0==(m&3));for(a=m+(g&-4);d<a;d+=4)B[d>>2]=0;for(a=m+g;d<a;)H[d++>>0]=0;return m}if("i8"===h)return a.subarray||a.slice?I.set(a,m):I.set(new Uint8Array(a),m),m;d=0;for(var r,t;d<g;)f=a[d],"function"===typeof f&&(f=u.md(f)),c=h||b[d],0===c?d++:("i64"==c&&(c="i32"),pa(m+d,f,
c),t!==c&&(r=u.va(c),t=c),d+=r);return m}e.allocate=ya;e.getMemory=function(a){return Aa?Ba?za(a):u.qa(a):u.ga(a)};function F(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=I[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,I.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return e.UTF8ToString(a)}e.Pointer_stringify=F;e.AsciiToString=function(a){for(var b="";;){var c=H[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}};
e.stringToAscii=function(a,b){return Ca(a,b,!1)};var Da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ea(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b,c));for(var d,f,g,h,m,r,c="";;){d=a[b++];if(!d)return c;d&128?(f=a[b++]&63,192==(d&224)?c+=String.fromCharCode((d&31)<<6|f):(g=a[b++]&63,224==(d&240)?d=(d&15)<<12|f<<6|g:(h=a[b++]&63,240==(d&248)?d=(d&7)<<18|f<<12|g<<6|h:(m=a[b++]&63,248==(d&252)?d=(d&3)<<24|f<<18|g<<12|h<<6|m:(r=a[b++]&63,d=(d&1)<<30|f<<24|g<<18|h<<12|m<<6|r))),65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>
10,56320|d&1023)))):c+=String.fromCharCode(d)}}e.UTF8ArrayToString=Ea;e.UTF8ToString=function(a){return Ea(I,a)};
function Fa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}e.stringToUTF8Array=Fa;function oa(a,b,c){return Fa(a,I,b,c)}e.stringToUTF8=oa;function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}e.lengthBytesUTF8=Ga;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function Ha(a){return a.replace(/__Z[\w\d_]+/g,function(a){var c;a:{var d=e.___cxa_demangle||e.__cxa_demangle;if(d)try{var f=a.substr(1),g=Ga(f)+1,h=za(g);oa(f,h,g);var m=za(4),r=d(h,0,0,m);if(0===xa(m,"i32")&&r){c=F(r);break a}}catch(t){}finally{h&&Ia(h),m&&Ia(m),r&&Ia(r)}else u.A("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");c=a}return a===c?a:a+" ["+c+"]"})}
function Ja(){var a;a:{a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}e.extraStackTrace&&(a+="\n"+e.extraStackTrace());return Ha(a)}e.stackTrace=Ja;var buffer,H,I,qa,Ka,B,La,va,wa;
function Ma(){e.HEAP8=H=new Int8Array(buffer);e.HEAP16=qa=new Int16Array(buffer);e.HEAP32=B=new Int32Array(buffer);e.HEAPU8=I=new Uint8Array(buffer);e.HEAPU16=Ka=new Uint16Array(buffer);e.HEAPU32=La=new Uint32Array(buffer);e.HEAPF32=va=new Float32Array(buffer);e.HEAPF64=wa=new Float64Array(buffer)}var Na,y,Aa,Oa,q,Pa,Qa,ha;Na=y=Oa=q=Pa=Qa=ha=0;Aa=!1;
function ia(){E("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+C+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ra=e.TOTAL_STACK||5242880,C=e.TOTAL_MEMORY||16777216;C<Ra&&e.N("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+C+"! (TOTAL_STACK="+Ra+")");
e.buffer?buffer=e.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:C/65536,maximum:C/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(C);Ma();B[0]=1668509029;qa[1]=25459;if(115!==I[2]||99!==I[3])throw"Runtime error: expected the system to be little-endian!";e.HEAP=void 0;e.buffer=buffer;e.HEAP8=H;e.HEAP16=qa;e.HEAP32=B;e.HEAPU8=I;e.HEAPU16=Ka;e.HEAPU32=La;e.HEAPF32=va;e.HEAPF64=wa;
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.gd;"number"===typeof c?void 0===b.W?e.dynCall_v(c):e.dynCall_vi(c,b.W):c(void 0===b.W?null:b.W)}}}var Ua=[],Va=[],Wa=[],Xa=[],Ya=[],Ba=!1;function Za(a){Ua.unshift(a)}e.addOnPreRun=Za;e.addOnInit=function(a){Va.unshift(a)};e.addOnPreMain=function(a){Wa.unshift(a)};e.addOnExit=function(a){Xa.unshift(a)};function $a(a){Ya.unshift(a)}e.addOnPostRun=$a;
function ab(a,b,c){c=Array(0<c?c:Ga(a)+1);a=Fa(a,c,0,c.length);b&&(c.length=a);return c}e.intArrayFromString=ab;e.intArrayToString=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];255<d&&(d&=255);b.push(String.fromCharCode(d))}return b.join("")};e.writeStringToMemory=function(a,b,c){u.A("writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!");var d,f;c&&(f=b+Ga(a),d=H[f]);oa(a,b,Infinity);c&&(H[f]=d)};function na(a,b){H.set(a,b)}e.writeArrayToMemory=na;
function Ca(a,b,c){for(var d=0;d<a.length;++d)H[b++>>0]=a.charCodeAt(d);c||(H[b>>0]=0)}e.writeAsciiToMemory=Ca;Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16)*d+c*(b>>>16)<<16)|0});Math.nd=Math.imul;if(!Math.fround){var bb=new Float32Array(1);Math.fround=function(a){bb[0]=a;return bb[0]}}Math.ed=Math.fround;Math.clz32||(Math.clz32=function(a){a=a>>>0;for(var b=0;32>b;b++)if(a&1<<31-b)return b;return 32});Math.bd=Math.clz32;
Math.trunc||(Math.trunc=function(a){return 0>a?Math.ceil(a):Math.floor(a)});Math.trunc=Math.trunc;var ra=Math.abs,ua=Math.ceil,ta=Math.floor,sa=Math.min,db=0,eb=null,fb=null;function gb(){db++;e.monitorRunDependencies&&e.monitorRunDependencies(db)}e.addRunDependency=gb;function hb(){db--;e.monitorRunDependencies&&e.monitorRunDependencies(db);if(0==db&&(null!==eb&&(clearInterval(eb),eb=null),fb)){var a=fb;fb=null;a()}}e.removeRunDependency=hb;e.preloadedImages={};e.preloadedAudios={};var J=null;
(function(a){function b(b){var c=a.usingWasm?65536:16777216;0<b%c&&(b+=c-b%c);var c=a.buffer,d=c.byteLength;if(a.usingWasm)try{return-1!==a.wasmMemory.grow((b-d)/65536)?a.buffer=a.wasmMemory.buffer:null}catch(f){return null}else return w.__growWasmMemory((b-d)/65536),a.buffer!==c?a.buffer:null}function c(a,b){var c=z;if(0>a.indexOf("."))c=(c||{})[a];else var d=a.split("."),c=(c||{})[d[0]],c=(c||{})[d[1]];b&&(c=(c||{})[b]);void 0===c&&E("bad lookupImport to ("+a+")."+b);return c}function d(b){var c=
a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");var c=new Int8Array(c),d=new Int8Array(b);J||c.set(d.subarray(a.STATIC_BASE,a.STATIC_BASE+a.STATIC_BUMP),a.STATIC_BASE);d.set(c);e.buffer=buffer=b;Ma()}function f(){var b;if(a.wasmBinary)b=a.wasmBinary,b=new Uint8Array(b);else if(a.readBinary)b=a.readBinary(p);else throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";
return b}function g(){return a.wasmBinary||"function"!==typeof fetch?new Promise(function(a){a(f())}):fetch(p,{cd:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+p+"'";return a.arrayBuffer()})}function h(b,c,d){if("function"!==typeof a.asm||a.asm===M)a.asmPreload?a.asm=a.asmPreload:eval(a.read(v));return"function"!==typeof a.asm?(a.printErr("asm evalling did not set the module properly"),!1):a.asm(b,c,d)}function m(b,c){function f(b){w=b.exports;w.memory&&d(w.memory);
a.asm=w;a.usingWasm=!0;hb()}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;c.memory=a.wasmMemory;z.global={NaN:NaN,Infinity:Infinity};z["global.Math"]=b.Math;z.env=c;gb();if(a.instantiateWasm)try{return a.instantiateWasm(z,f)}catch(h){return a.printErr("Module.instantiateWasm callback failed with error: "+h),!1}g().then(function(a){return WebAssembly.instantiate(a,
z)}).then(function(a){f(a.instance)}).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);a.quit(1,b)});return{}}var r=a.wasmJSMethod||"native-wasm";a.wasmJSMethod=r;var t=a.wasmTextFile||"trezor-crypto.wast",p=a.wasmBinaryFile||"trezor-crypto.wasm",v=a.asmjsCodeFile||"trezor-crypto.temp.asm.js";"function"===typeof a.locateFile&&(t=a.locateFile(t),p=a.locateFile(p),v=a.locateFile(v));var z={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"f64-to-int":function(a){return a|
0},"i32s-div":function(a,b){return(a|0)/(b|0)|0},"i32u-div":function(a,b){return(a>>>0)/(b>>>0)>>>0},"i32s-rem":function(a,b){return(a|0)%(b|0)|0},"i32u-rem":function(a,b){return(a>>>0)%(b>>>0)>>>0},"debugger":function(){debugger}},parent:a},w=null;a.asmPreload=a.asm;var x=a.reallocBuffer;a.reallocBuffer=function(a){return"asmjs"===K?x(a):b(a)};var K="";a.asm=function(b,g,p){if(!g.table){var x=a.wasmTableSize;void 0===x&&(x=1024);var M=a.wasmMaxTableSize;g.table="object"===typeof WebAssembly&&"function"===
typeof WebAssembly.Table?void 0!==M?new WebAssembly.Table({initial:x,maximum:M,element:"anyfunc"}):new WebAssembly.Table({initial:x,element:"anyfunc"}):Array(x);a.wasmTable=g.table}g.memoryBase||(g.memoryBase=a.STATIC_BASE);g.tableBase||(g.tableBase=0);for(var A,x=r.split(","),M=0;M<x.length;M++)if(K=A=x[M],"native-wasm"===A){if(A=m(b,g))break}else if("asmjs"===A){if(A=h(b,g,p))break}else if("interpret-asm2wasm"===A||"interpret-s-expr"===A||"interpret-binary"===A){var Q=b,G=g,cb=p;if("function"!==
typeof WasmJS)a.printErr("WasmJS not detected - polyfill not bundled?"),A=!1;else{var D=WasmJS({});D.outside=a;D.info=z;D.lookupImport=c;assert(cb===a.buffer);z.global=Q;z.env=G;assert(cb===a.buffer);G.memory=cb;assert(G.memory instanceof ArrayBuffer);D.providedTotalMemory=a.buffer.byteLength;Q=void 0;Q="interpret-binary"===A?f():a.read("interpret-asm2wasm"==A?v:t);G=void 0;if("interpret-asm2wasm"==A)G=D._malloc(Q.length+1),D.writeAsciiToMemory(Q,G),D._load_asm2wasm(G);else if("interpret-s-expr"===
A)G=D._malloc(Q.length+1),D.writeAsciiToMemory(Q,G),D._load_s_expr2wasm(G);else if("interpret-binary"===A)G=D._malloc(Q.length),D.HEAPU8.set(Q,G),D._load_binary2wasm(G,Q.length);else throw"what? "+A;D._free(G);D._instantiate(G);a.newBuffer&&(d(a.newBuffer),a.newBuffer=null);A=w=D.asmExports}if(A)break}else throw"bad method: "+A;if(!A)throw"no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods";
return A};var M=a.asm})(e);Na=u.U;y=Na+41744;Va.push();J=0<=e.wasmJSMethod.indexOf("asmjs")||0<=e.wasmJSMethod.indexOf("interpret-asm2wasm")?"trezor-crypto.js.mem":null;e.STATIC_BASE=Na;e.STATIC_BUMP=41744;var ib=y;y+=16;e._memset=jb;
var L={t:1,m:2,Jc:3,Gb:4,p:5,la:6,Za:7,dc:8,I:9,nb:10,ha:11,Tc:11,Fa:12,Q:13,zb:14,pc:15,R:16,ia:17,Uc:18,T:19,ja:20,B:21,g:22,Zb:23,Ea:24,s:25,Qc:26,Ab:27,lc:28,J:29,Gc:30,Sb:31,zc:32,wb:33,Dc:34,hc:42,Db:43,ob:44,Jb:45,Kb:46,Lb:47,Rb:48,Rc:49,bc:50,Ib:51,tb:35,ec:37,fb:52,ib:53,Vc:54,$b:55,jb:56,kb:57,ub:35,lb:59,nc:60,cc:61,Nc:62,mc:63,ic:64,jc:65,Fc:66,fc:67,bb:68,Kc:69,pb:70,Ac:71,Ub:72,xb:73,hb:74,uc:76,gb:77,Ec:78,Mb:79,Nb:80,Qb:81,Pb:82,Ob:83,oc:38,ka:39,Vb:36,S:40,vc:95,yc:96,sb:104,ac:105,
cb:97,Cc:91,sc:88,kc:92,Hc:108,rb:111,$a:98,qb:103,Yb:101,Wb:100,Oc:110,Bb:112,Cb:113,Fb:115,eb:114,vb:89,Tb:90,Bc:93,Ic:94,ab:99,Xb:102,Hb:106,qc:107,Pc:109,Sc:87,yb:122,Lc:116,tc:95,gc:123,Eb:84,wc:75,mb:125,rc:131,xc:130,Mc:86},kb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function lb(a){e.___errno_location&&(B[e.___errno_location()>>2]=a);return a}
function mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c--;c)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function qb(){var a=Array.prototype.slice.call(arguments,0);return nb(a.join("/"))}function N(a,b){return nb(a+"/"+b)}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],v:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.c.rdev];if(!b)throw new O(L.T);a.tty=b;a.seekable=!1},close:function(a){a.tty.v.flush(a.tty)},flush:function(a){a.tty.v.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.v.wa)throw new O(L.la);for(var f=0,g=0;g<d;g++){var h;try{h=a.tty.v.wa(a.tty)}catch(m){throw new O(L.p);}if(void 0===h&&0===f)throw new O(L.ha);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.c.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.v.da)throw new O(L.la);
for(var f=0;f<d;f++)try{a.tty.v.da(a.tty,b[c+f])}catch(g){throw new O(L.p);}d&&(a.c.timestamp=Date.now());return f}},wb={wa:function(a){if(!a.input.length){var b=null;if(n){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(m){if(-1!=m.toString().indexOf("EOF"))d=0;else throw m;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==
typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ab(b,!0)}return a.input.shift()},da:function(a,b){null===b||10===b?(e.print(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(Ea(a.output,0)),a.output=[])}},xb={da:function(a,b){null===b||10===b?(e.printErr(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(Ea(a.output,0)),a.output=[])}},P={k:null,i:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(L.t);P.k||(P.k={dir:{c:{l:P.d.l,h:P.d.h,lookup:P.d.lookup,D:P.d.D,rename:P.d.rename,unlink:P.d.unlink,rmdir:P.d.rmdir,readdir:P.d.readdir,symlink:P.d.symlink},stream:{o:P.e.o}},file:{c:{l:P.d.l,h:P.d.h},stream:{o:P.e.o,read:P.e.read,write:P.e.write,na:P.e.na,Aa:P.e.Aa,Ca:P.e.Ca}},link:{c:{l:P.d.l,
h:P.d.h,readlink:P.d.readlink},stream:{}},pa:{c:{l:P.d.l,h:P.d.h},stream:yb}});c=zb(a,b,c,d);R(c.mode)?(c.d=P.k.dir.c,c.e=P.k.dir.stream,c.b={}):32768===(c.mode&61440)?(c.d=P.k.file.c,c.e=P.k.file.stream,c.f=0,c.b=null):40960===(c.mode&61440)?(c.d=P.k.link.c,c.e=P.k.link.stream):8192===(c.mode&61440)&&(c.d=P.k.pa.c,c.e=P.k.pa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ma:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.f;++c)b.push(a.b[c]);return b}return a.b},kd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.f):new Uint8Array(a.b):new Uint8Array},ra:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=P.Ma(a),a.f=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.f&&a.b.set(c.subarray(0,a.f),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Ua:function(a,b){if(a.f!=b)if(0==b)a.b=null,a.f=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.f)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.f=b}},d:{l:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;R(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.f:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.q=4096;b.blocks=Math.ceil(b.size/b.q);return b},
h:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Ua(a,b.size)},lookup:function(){throw Ab[L.m];},D:function(a,b,c,d){return P.createNode(a,b,c,d)},rename:function(a,b,c){if(R(a.mode)){var d;try{d=Bb(b,c)}catch(f){}if(d)for(var g in d.b)throw new O(L.ka);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Bb(a,b),d;for(d in c.b)throw new O(L.ka);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new O(L.g);return a.link}},e:{read:function(a,b,c,d,f){var g=a.c.b;if(f>=a.c.f)return 0;a=Math.min(a.c.f-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.c;a.timestamp=Date.now();if(b.subarray&&(!a.b||
a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.f=d;if(0===a.f&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.f=d;if(f+d<=a.f)return a.b.set(b.subarray(c,c+d),f),d}P.ra(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.f=Math.max(a.f,f+d);return d},o:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.c.mode&61440)&&(b+=a.c.f);if(0>b)throw new O(L.g);return b},na:function(a,b,c){P.ra(a.c,b+c);a.c.f=Math.max(a.c.f,b+c)},Aa:function(a,
b,c,d,f,g,h){if(32768!==(a.c.mode&61440))throw new O(L.T);c=a.c.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.c.f)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=za(d);if(!d)throw new O(L.Fa);b.set(c,d)}else a=!1,d=c.byteOffset;return{ud:d,Yc:a}},Ca:function(a,b,c,d,f){if(32768!==(a.c.mode&61440))throw new O(L.T);if(f&2)return 0;P.e.write(a,b,0,d,c,!1);return 0}}},S={M:!1,Xa:function(){S.M=!!process.platform.match(/^win/)},i:function(a){assert(n);return S.createNode(null,
"/",S.ua(a.ba.root),0)},createNode:function(a,b,c){if(!R(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new O(L.g);a=zb(a,b,c);a.d=S.d;a.e=S.e;return a},ua:function(a){var b;try{b=fs.lstatSync(a),S.M&&(b.mode=b.mode|(b.mode&146)>>1)}catch(c){if(!c.code)throw c;throw new O(L[c.code]);}return b.mode},j:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.i.ba.root);b.reverse();return qb.apply(null,b)},sa:{0:"r",1:"r+",2:"r+",64:"r",65:"r+",66:"r+",129:"rx+",193:"rx+",514:"w+",577:"w",
578:"w+",705:"wx",706:"wx+",1024:"a",1025:"a",1026:"a+",1089:"a",1090:"a+",1153:"ax",1154:"ax+",1217:"ax",1218:"ax+",4096:"rs",4098:"rs+"},La:function(a){a&=-2099201;a&=-32769;a&=-524289;if(a in S.sa)return S.sa[a];throw new O(L.g);},d:{l:function(a){a=S.j(a);var b;try{b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new O(L[c.code]);}S.M&&!b.q&&(b.q=4096);S.M&&!b.blocks&&(b.blocks=(b.size+b.q-1)/b.q|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,
atime:b.atime,mtime:b.mtime,ctime:b.ctime,q:b.q,blocks:b.blocks}},h:function(a,b){var c=S.j(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new O(L[d.code]);}},lookup:function(a,b){var c=N(S.j(a),b),c=S.ua(c);return S.createNode(a,b,c)},D:function(a,b,c,d){a=S.createNode(a,b,c,d);b=S.j(a);try{R(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new O(L[f.code]);
}return a},rename:function(a,b,c){a=S.j(a);b=N(S.j(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new O(L[d.code]);}},unlink:function(a,b){var c=N(S.j(a),b);try{fs.unlinkSync(c)}catch(d){if(!d.code)throw d;throw new O(L[d.code]);}},rmdir:function(a,b){var c=N(S.j(a),b);try{fs.rmdirSync(c)}catch(d){if(!d.code)throw d;throw new O(L[d.code]);}},readdir:function(a){a=S.j(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new O(L[b.code]);}},symlink:function(a,b,c){a=N(S.j(a),
b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new O(L[d.code]);}},readlink:function(a){var b=S.j(a);try{return b=fs.readlinkSync(b),b=Cb.relative(Cb.resolve(a.i.ba.root),b)}catch(c){if(!c.code)throw c;throw new O(L[c.code]);}}},e:{open:function(a){var b=S.j(a.c);try{32768===(a.c.mode&61440)&&(a.G=fs.openSync(b,S.La(a.flags)))}catch(c){if(!c.code)throw c;throw new O(L[c.code]);}},close:function(a){try{32768===(a.c.mode&61440)&&a.G&&fs.closeSync(a.G)}catch(b){if(!b.code)throw b;throw new O(L[b.code]);
}},read:function(a,b,c,d,f){if(0===d)return 0;var g=new Buffer(d),h;try{h=fs.readSync(a.G,g,0,d,f)}catch(m){throw new O(L[m.code]);}if(0<h)for(a=0;a<h;a++)b[c+a]=g[a];return h},write:function(a,b,c,d,f){b=new Buffer(b.subarray(c,c+d));var g;try{g=fs.writeSync(a.G,b,0,d,f)}catch(h){throw new O(L[h.code]);}return g},o:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.c.mode&61440))try{b+=fs.fstatSync(a.G).size}catch(d){throw new O(L[d.code]);}if(0>b)throw new O(L.g);return b}}};y+=16;
y+=16;y+=16;var Db=null,Eb=[null],Fb=[],Gb=1,T=null,Hb=!0,U={},O=null,Ab={};
function V(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",c:null};var c={ta:!0,ea:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ea)throw new O(L.S);var c=mb(a.split("/").filter(function(a){return!!a}),!1),f=Db;d="/";for(var g=0;g<c.length;g++){var h=g===c.length-1;if(h&&b.parent)break;f=Bb(f,c[g]);d=N(d,c[g]);f.F&&(!h||h&&b.ta)&&(f=f.F.root);if(!h||b.Y)for(h=0;40960===(f.mode&61440);)if(f=Ib(d),d=rb(ob(d),f),f=V(d,{ea:b.ea}).c,40<h++)throw new O(L.S);}return{path:d,c:f}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.i.Ba,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%T.length}function Lb(a){var b=Kb(a.parent.id,a.name);a.u=T[b];T[b]=a}function Bb(a,b){var c;if(c=(c=Mb(a,"x"))?c:a.d.lookup?0:L.Q)throw new O(c,a);for(c=T[Kb(a.id,b)];c;c=c.u){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.d.lookup(a,b)}
function zb(a,b,c,d){Nb||(Nb=function(a,b,c,d){a||(a=this);this.parent=a;this.i=a.i;this.F=null;this.id=Gb++;this.name=b;this.mode=c;this.d={};this.e={};this.rdev=d},Nb.prototype={},Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ra:{get:function(){return R(this.mode)}},Qa:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Nb(a,b,c,d);Lb(a);return a}function R(a){return 16384===(a&61440)}var Ob={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Pb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Mb(a,b){if(Hb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return L.Q}else return L.Q;return 0}
function Qb(a,b){try{return Bb(a,b),L.ia}catch(c){}return Mb(a,"wx")}function Rb(a){var b;b=4096;for(a=a||0;a<=b;a++)if(!Fb[a])return a;throw new O(L.Ea);}
function Sb(a,b){Tb||(Tb=function(){},Tb.prototype={},Object.defineProperties(Tb.prototype,{object:{get:function(){return this.c},set:function(a){this.c=a}},qd:{get:function(){return 1!==(this.flags&2097155)}},rd:{get:function(){return 0!==(this.flags&2097155)}},pd:{get:function(){return this.flags&1024}}}));var c=new Tb,d;for(d in a)c[d]=a[d];a=c;c=Rb(b);a.fd=c;return Fb[c]=a}var yb={open:function(a){a.e=Eb[a.c.rdev].e;a.e.open&&a.e.open(a)},o:function(){throw new O(L.J);}};
function ub(a,b){Eb[a]={e:b}}function Ub(a,b){var c="/"===b,d=!b,f;if(c&&Db)throw new O(L.R);if(!c&&!d){f=V(b,{ta:!1});b=f.path;f=f.c;if(f.F)throw new O(L.R);if(!R(f.mode))throw new O(L.ja);}var d={type:a,ba:{},Ba:b,Sa:[]},g=a.i(d);g.i=d;d.root=g;c?Db=g:f&&(f.F=d,f.i&&f.i.Sa.push(d))}function Vb(a,b,c){var d=V(a,{parent:!0}).c;a=pb(a);if(!a||"."===a||".."===a)throw new O(L.g);var f=Qb(d,a);if(f)throw new O(f);if(!d.d.D)throw new O(L.t);return d.d.D(d,a,b,c)}
function Wb(a,b){b=(void 0!==b?b:438)&4095;b|=32768;return Vb(a,b,0)}function W(a,b){b=(void 0!==b?b:511)&1023;b|=16384;return Vb(a,b,0)}function Xb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Vb(a,b|8192,c)}function Yb(a,b){if(!rb(a))throw new O(L.m);var c=V(b,{parent:!0}).c;if(!c)throw new O(L.m);var d=pb(b),f=Qb(c,d);if(f)throw new O(f);if(!c.d.symlink)throw new O(L.t);return c.d.symlink(c,d,a)}
function Ib(a){a=V(a).c;if(!a)throw new O(L.m);if(!a.d.readlink)throw new O(L.g);return rb(Jb(a.parent),a.d.readlink(a))}function Zb(a,b){var c;"string"===typeof a?c=V(a,{Y:!0}).c:c=a;if(!c.d.h)throw new O(L.t);c.d.h(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function $b(a,b,c,d){if(""===a)throw new O(L.m);if("string"===typeof b){var f=Ob[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;var g;if("object"===typeof a)g=a;else{a=nb(a);try{g=V(a,{Y:!(b&131072)}).c}catch(h){}}f=!1;if(b&64)if(g){if(b&128)throw new O(L.ia);}else g=Vb(a,c,0),f=!0;if(!g)throw new O(L.m);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!R(g.mode))throw new O(L.ja);if(!f&&(c=g?40960===(g.mode&61440)?L.S:R(g.mode)&&
("r"!==Pb(b)||b&512)?L.B:Mb(g,Pb(b)):L.m))throw new O(c);if(b&512){c=g;var m;"string"===typeof c?m=V(c,{Y:!0}).c:m=c;if(!m.d.h)throw new O(L.t);if(R(m.mode))throw new O(L.B);if(32768!==(m.mode&61440))throw new O(L.g);if(c=Mb(m,"w"))throw new O(c);m.d.h(m,{size:0,timestamp:Date.now()})}b&=-641;d=Sb({c:g,path:Jb(g),flags:b,seekable:!0,position:0,e:g.e,Ya:[],error:!1},d);d.e.open&&d.e.open(d);!e.logReadFiles||b&1||(ac||(ac={}),a in ac||(ac[a]=1,e.printErr("read file: "+a)));try{U.onOpenFile&&(g=0,1!==
(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),U.onOpenFile(a,g))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function bc(a){a.$&&(a.$=null);try{a.e.close&&a.e.close(a)}catch(b){throw b;}finally{Fb[a.fd]=null}}function cc(a,b,c){if(!a.seekable||!a.e.o)throw new O(L.J);a.position=a.e.o(a,b,c);a.Ya=[]}
function dc(a,b,c,d,f,g){if(0>d||0>f)throw new O(L.g);if(0===(a.flags&2097155))throw new O(L.I);if(R(a.c.mode))throw new O(L.B);if(!a.e.write)throw new O(L.g);a.flags&1024&&cc(a,0,2);var h=!0;if("undefined"===typeof f)f=a.position,h=!1;else if(!a.seekable)throw new O(L.J);b=a.e.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&U.onWriteToFile)U.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+m.message)}return b}
function ec(){O||(O=function(a,b){this.c=b;this.Wa=function(a){this.n=a;for(var b in L)if(L[b]===a){this.code=b;break}};this.Wa(a);this.message=kb[a]},O.prototype=Error(),O.prototype.constructor=O,[L.m].forEach(function(a){Ab[a]=new O(a);Ab[a].stack="<generic error, no stack>"}))}var fc;function gc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function hc(a,b,c,d){a=N("string"===typeof a?a:Jb(a),b);return Wb(a,gc(c,d))}
function ic(a,b,c,d,f,g){a=b?N("string"===typeof a?a:Jb(a),b):a;d=gc(d,f);f=Wb(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Zb(f,d|146);a=$b(f,"w");dc(a,c,0,c.length,0,g);bc(a);Zb(f,d)}return f}
function X(a,b,c,d){a=N("string"===typeof a?a:Jb(a),b);b=gc(!!c,!!d);X.za||(X.za=64);var f=X.za++<<8|0;ub(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var t=0,p=0;p<f;p++){var v;try{v=c()}catch(z){throw new O(L.p);}if(void 0===v&&0===t)throw new O(L.ha);if(null===v||void 0===v)break;t++;b[d+p]=v}t&&(a.c.timestamp=Date.now());return t},write:function(a,b,c,f){for(var t=0;t<f;t++)try{d(b[c+t])}catch(p){throw new O(L.p);}f&&(a.c.timestamp=
Date.now());return t}});return Xb(a,b,f)}
function jc(a){if(a.Qa||a.Ra||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=ab(e.read(a.url),!0),a.f=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||lb(L.p);return b}var kc={},Nb,Tb,ac,Y=0;
function Z(){Y+=4;return B[Y-4>>2]}function lc(){var a;a=Z();a=Fb[a];if(!a)throw new O(L.I);return a}e._sbrk=mc;function nc(){nc.C||(nc.C=[]);nc.C.push(u.P());return nc.C.length-1}e._llvm_bswap_i32=oc;e._memcpy=pc;ec();T=Array(4096);Ub(P,"/");W("/tmp");W("/home");W("/home/web_user");
(function(){W("/dev");ub(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Xb("/dev/null",259);tb(1280,wb);tb(1536,xb);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a;if("undefined"!==typeof crypto){var b=new Uint8Array(1);a=function(){crypto.getRandomValues(b);return b[0]}}else a=n?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};X("/dev","random",a);X("/dev","urandom",a);W("/dev/shm");W("/dev/shm/tmp")})();W("/proc");W("/proc/self");W("/proc/self/fd");
Ub({i:function(){var a=zb("/proc/self","fd",16895,73);a.d={lookup:function(a,c){var d=Fb[+c];if(!d)throw new O(L.I);var f={parent:null,i:{Ba:"fake"},d:{readlink:function(){return d.path}}};return f.parent=f}};return a}},"/proc/self/fd");
Va.unshift(function(){if(!e.noFSInit&&!fc){assert(!fc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");fc=!0;ec();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?X("/dev","stdin",e.stdin):Yb("/dev/tty","/dev/stdin");e.stdout?X("/dev","stdout",null,e.stdout):Yb("/dev/tty","/dev/stdout");e.stderr?X("/dev","stderr",null,e.stderr):Yb("/dev/tty1","/dev/stderr");var a=
$b("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=$b("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=$b("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Wa.push(function(){Hb=!1});Xa.push(function(){fc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Fb.length;a++){var b=Fb[a];b&&bc(b)}});e.FS_createFolder=function(a,b,c,d){a=N("string"===typeof a?a:Jb(a),b);return W(a,gc(c,d))};
e.FS_createPath=function(a,b){a="string"===typeof a?a:Jb(a);for(var c=b.split("/").reverse();c.length;){var d=c.pop();if(d){var f=N(a,d);try{W(f)}catch(g){}a=f}}return f};e.FS_createDataFile=ic;
e.FS_createPreloadedFile=function(a,b,c,d,f,g,h,m,r,t){function p(c){function p(c){t&&t();m||ic(a,b,c,d,f,r);g&&g();hb()}var x=!1;e.preloadPlugins.forEach(function(a){!x&&a.canHandle(v)&&(a.handle(c,v,p,function(){h&&h();hb()}),x=!0)});x||p(c)}Browser.od();var v=b?rb(N(a,b)):a;gb();"string"==typeof c?Browser.$c(c,function(a){p(a)},h):p(c)};
e.FS_createLazyFile=function(a,b,c,d,f){var g,h;function m(){this.aa=!1;this.K=[]}m.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.ya(a/this.chunkSize|0)[b]}};m.prototype.Va=function(a){this.ya=a};m.prototype.oa=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d,a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d,g=1048576;f||(g=b);var h=this;h.Va(function(a){var d=a*g,f=(a+1)*g-1,f=Math.min(f,b-1);if("undefined"===typeof h.K[a]){var m=h.K;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==g&&p.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):ab(p.responseText||"",!0);m[a]=d}if("undefined"===typeof h.K[a])throw Error("doXHR failed!");return h.K[a]});if(a||!b)g=b=1,g=b=this.ya(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ha=b;this.Ga=
g;this.aa=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";g=new m;Object.defineProperties(g,{length:{get:function(){this.aa||this.oa();return this.Ha}},chunkSize:{get:function(){this.aa||this.oa();return this.Ga}}});h=void 0}else h=c,g=void 0;var r=hc(a,b,d,f);g?r.b=g:h&&(r.b=null,r.url=h);Object.defineProperties(r,{f:{get:function(){return this.b.length}}});var t={};Object.keys(r.e).forEach(function(a){var b=
r.e[a];t[a]=function(){if(!jc(r))throw new O(L.p);return b.apply(null,arguments)}});t.read=function(a,b,c,d,f){if(!jc(r))throw new O(L.p);a=a.c.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};r.e=t;return r};e.FS_createLink=function(a,b,c){a=N("string"===typeof a?a:Jb(a),b);return Yb(c,a)};e.FS_createDevice=X;
e.FS_unlink=function(a){var b=V(a,{parent:!0}).c,c=pb(a),d=Bb(b,c),f;a:{try{f=Bb(b,c)}catch(g){f=g.n;break a}var h=Mb(b,"wx");f=h?h:R(f.mode)?L.B:0}if(f)throw new O(f);if(!b.d.unlink)throw new O(L.t);if(d.F)throw new O(L.R);try{U.willDeletePath&&U.willDeletePath(a)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+m.message)}b.d.unlink(b,c);b=Kb(d.parent.id,d.name);if(T[b]===d)T[b]=d.u;else for(b=T[b];b;){if(b.u===d){b.u=d.u;break}b=b.u}try{if(U.onDeletePath)U.onDeletePath(a)}catch(r){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+r.message)}};Va.unshift(function(){});Xa.push(function(){});if(n){var fs=require("fs"),Cb=require("path");S.Xa()}ha=ya(1,"i32",2);Oa=q=u.ma(y);Pa=Oa+Ra;Qa=u.ma(Pa);B[ha>>2]=Qa;Aa=!0;e.wasmTableSize=10;e.wasmMaxTableSize=10;e.Ja={Math:Math,Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array,Uint32Array:Uint32Array,Float32Array:Float32Array,Float64Array:Float64Array,NaN:NaN,Infinity:Infinity};
e.Ka={abort:E,assert:assert,enlargeMemory:function(){ia()},getTotalMemory:function(){return C},abortOnCannotGrowMemory:ia,invoke_ii:function(a,b){try{return e.dynCall_ii(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_iiii:function(a,b,c,d){try{return e.dynCall_iiii(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},___syscall221:function(a,b){Y=b;try{var c=lc();switch(Z()){case 0:var d=Z();return 0>d?-L.g:$b(c.path,c.flags,0,d).fd;
case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Z(),c.flags|=d,0;case 12:case 12:return d=Z(),qa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-L.g;case 9:return lb(L.g),-1;default:return-L.g}}catch(f){return"undefined"!==typeof kc&&f instanceof O||E(f),-f.n}},_llvm_bswap_i64:function(a,b){var c=oc(b)>>>0,d=oc(a)>>>0;return(u.Da(d),c)|0},___lock:function(){},_abort:function(){e.abort()},___setErrNo:lb,___syscall6:function(a,b){Y=b;try{var c=lc();bc(c);return 0}catch(d){return"undefined"!==
typeof kc&&d instanceof O||E(d),-d.n}},_llvm_stacksave:nc,___unlock:function(){},___syscall5:function(a,b){Y=b;try{var c=F(Z()),d=Z(),f=Z();return $b(c,d,f).fd}catch(g){return"undefined"!==typeof kc&&g instanceof O||E(g),-g.n}},_emscripten_memcpy_big:function(a,b,c){I.set(I.subarray(b,b+c),a);return a},___syscall54:function(a,b){Y=b;try{var c=lc(),d=Z();switch(d){case 21505:return c.tty?0:-L.s;case 21506:return c.tty?0:-L.s;case 21519:if(!c.tty)return-L.s;var f=Z();return B[f>>2]=0;case 21520:return c.tty?
-L.g:-L.s;case 21531:f=Z();if(!c.e.Pa)throw new O(L.s);return c.e.Pa(c,d,f);case 21523:return c.tty?0:-L.s;default:E("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof kc&&g instanceof O||E(g),-g.n}},___syscall140:function(a,b){Y=b;try{var c=lc();Z();var d=Z(),f=Z(),g=Z();cc(c,d,g);B[f>>2]=c.position;c.$&&0===d&&0===g&&(c.$=null);return 0}catch(h){return"undefined"!==typeof kc&&h instanceof O||E(h),-h.n}},_llvm_stackrestore:function(a){var b=nc.C[a];nc.C.splice(a,1);u.H(b)},___assert_fail:function(a,
b,c,d){ja=!0;throw"Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",c,d?F(d):"unknown function"]+" at "+Ja();},___syscall145:function(a,b){Y=b;try{var c=lc(),d=Z(),f;a:{for(var g=Z(),h=0,m=0;m<g;m++){var r=B[d+(8*m+4)>>2],t,p=c,v=B[d+8*m>>2],z=r,w=void 0,x=H;if(0>z||0>w)throw new O(L.g);if(1===(p.flags&2097155))throw new O(L.I);if(R(p.c.mode))throw new O(L.B);if(!p.e.read)throw new O(L.g);var K=!0;if("undefined"===typeof w)w=p.position,K=!1;else if(!p.seekable)throw new O(L.J);var M=p.e.read(p,
x,v,z,w);K||(p.position+=M);t=M;if(0>t){f=-1;break a}h+=t;if(t<r)break}f=h}return f}catch(Ta){return"undefined"!==typeof kc&&Ta instanceof O||E(Ta),-Ta.n}},___syscall146:function(a,b){Y=b;try{var c=lc(),d=Z(),f;a:{for(var g=Z(),h=0,m=0;m<g;m++){var r=dc(c,H,B[d+8*m>>2],B[d+(8*m+4)>>2],void 0);if(0>r){f=-1;break a}h+=r}f=h}return f}catch(t){return"undefined"!==typeof kc&&t instanceof O||E(t),-t.n}},DYNAMICTOP_PTR:ha,tempDoublePtr:ib,ABORT:ja,STACKTOP:q,STACK_MAX:Pa};var qc=e.asm(e.Ja,e.Ka,buffer);
e.asm=qc;var za=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e.getTempRet0=function(){return e.asm.getTempRet0.apply(null,arguments)};e._fflush=function(){return e.asm._fflush.apply(null,arguments)};e.runPostSets=function(){return e.asm.runPostSets.apply(null,arguments)};e.setTempRet0=function(){return e.asm.setTempRet0.apply(null,arguments)};e._ecdsa_read_pubkey=function(){return e.asm._ecdsa_read_pubkey.apply(null,arguments)};
e.establishStackSpace=function(){return e.asm.establishStackSpace.apply(null,arguments)};e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};var jb=e._memset=function(){return e.asm._memset.apply(null,arguments)},mc=e._sbrk=function(){return e.asm._sbrk.apply(null,arguments)};e._emscripten_get_global_libc=function(){return e.asm._emscripten_get_global_libc.apply(null,arguments)};var pc=e._memcpy=function(){return e.asm._memcpy.apply(null,arguments)};
e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};var Ia=e._free=function(){return e.asm._free.apply(null,arguments)};e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)};e._hdnode_public_ckd_address_optimized=function(){return e.asm._hdnode_public_ckd_address_optimized.apply(null,arguments)};var oc=e._llvm_bswap_i32=function(){return e.asm._llvm_bswap_i32.apply(null,arguments)};
e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};u.O=e.stackAlloc;u.P=e.stackSave;u.H=e.stackRestore;u.dd=e.establishStackSpace;u.Da=e.setTempRet0;u.Oa=e.getTempRet0;e.asm=qc;
if(J)if("function"===typeof e.locateFile?J=e.locateFile(J):e.memoryInitializerPrefixURL&&(J=e.memoryInitializerPrefixURL+J),n||ca){var rc=e.readBinary(J);I.set(rc,u.U)}else{var tc=function(){e.readAsync(J,sc,function(){throw"could not load memory initializer "+J;})};gb();var sc=function(a){a.byteLength&&(a=new Uint8Array(a));I.set(a,u.U);e.memoryInitializerRequest&&delete e.memoryInitializerRequest.response;hb()};if(e.memoryInitializerRequest){var uc=function(){var a=e.memoryInitializerRequest;200!==
a.status&&0!==a.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+a.status+", retrying "+J),tc()):sc(a.response)};e.memoryInitializerRequest.response?setTimeout(uc,0):e.memoryInitializerRequest.addEventListener("load",uc)}else tc()}function ga(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ga.prototype=Error();ga.prototype.constructor=ga;
var vc=null,fb=function wc(){e.calledRun||xc();e.calledRun||(fb=wc)};e.callMain=e.ad=function(a){function b(){for(var a=0;3>a;a++)d.push(0)}a=a||[];Ba||(Ba=!0,Sa(Va));var c=a.length+1,d=[ya(ab(e.thisProgram),"i8",0)];b();for(var f=0;f<c-1;f+=1)d.push(ya(ab(a[f]),"i8",0)),b();d.push(0);d=ya(d,"i32",0);try{var g=e._main(c,d,0);yc(g,!0)}catch(h){h instanceof ga||("SimulateInfiniteLoop"==h?e.noExitRuntime=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),e.N("exception thrown: "+a),e.quit(1,h)))}finally{}};
function xc(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!ja)){Ba||(Ba=!0,Sa(Va));Sa(Wa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&zc&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)$a(e.postRun.shift());Sa(Ya)}}a=a||e.arguments;null===vc&&(vc=Date.now());if(!(0<db)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Za(e.preRun.shift());Sa(Ua);0<db||e.calledRun||(e.setStatus?(e.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=e.run=xc;function yc(a,b){if(!b||!e.noExitRuntime){if(!e.noExitRuntime&&(ja=!0,q=void 0,Sa(Xa),e.onExit))e.onExit(a);n&&process.exit(a);e.quit(a,new ga(a))}}e.exit=e.exit=yc;var Ac=[];
function E(a){void 0!==a?(e.print(a),e.N(a),a=JSON.stringify(a)):a="";ja=!0;var b="abort("+a+") at "+Ja()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";Ac&&Ac.forEach(function(c){b=c(b,a)});throw b;}e.abort=e.abort=E;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var zc=!0;e.noInitialRun&&(zc=!1);xc();var Bc=null,Cc=new Promise(function(a){Bc=a});
e.onRuntimeInitialized=function(){function a(a){var b=new Uint8Array(33);b.set(a.public_key,0);d.set(b,t);b=new Uint8Array(32);b.set(a.chain_code,0);d.set(b,p);h(0,t,r)}function b(a,b,c){g(r,p,a,b,v,60,c);return m(v)}function c(c,d,f,g,h){var m=[];a(c);for(c=d;c<=f;c++)m.push(b(c,g,h));return m}var d=e.HEAPU8,f=e._malloc,g=e._hdnode_public_ckd_address_optimized,h=e._ecdsa_read_pubkey,m=e.Pointer_stringify,r=f(72),t=f(33),p=f(32),v=f(60);Bc({processMessage:function(a){a=a.data;var b=a.type;switch(b){case "deriveAddressRange":b=
c(a.node,a.firstIndex,a.lastIndex,a.version,!!a.segwit);self.postMessage({addresses:b,firstIndex:a.firstIndex,lastIndex:a.lastIndex});break;default:throw Error("Unknown message type: "+b);}},serializeNode:a,deriveAddress:b,deriveAddressRange:c})};l&&(self.onmessage=function(a){Cc.then(function(b){b.processMessage(a)})});
if("undefined"!==typeof module){var Ec=function(a){return function(){if(null===Dc)throw Error("trezor-crypto not yet inited.");return Dc[a].apply(void 0,arguments)}},Dc=null,Fc=Cc.then(function(a){Dc=a});module.exports={serializeNode:Ec("serializeNode"),deriveAddress:Ec("deriveAddress"),deriveAddressRange:Ec("deriveAddressRange"),ready:Fc}};
